// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "video-recorder",
    platforms: [
        .iOS("13.0")
    ],
    products: [
        .iOSApplication(
            name: "video-recorder",
            targets: ["UIKItExampleModule"],
            bundleIdentifier: "jp.co.lacicu.vrdemo",
            teamIdentifier: "L6KA777G24",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "To Record Video"),
                .microphone(purposeString: "To Record Sounds"),
                .photoLibraryAdd(purposeString: "Save video to library")
            ]
        )
    ],
    dependencies: [
        .package(name: "APVideoRecorder", path: "/Users/kyosuke/Git/github.com/lacicu/common/swift-video-recorder")
    ],
    targets: [
        .executableTarget(
            name: "UIKItExampleModule",
            dependencies: [
                "APVideoRecorder"
            ]
        )
    ]
)